/* Generated by Yosys 0.11+50 (git sha1 707d98b06, gcc 11.2.0-7ubuntu2 -fPIC -Os) */

(* \amaranth.hierarchy  = "DuplexingPP" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module DuplexingPP(z, z_valid, z_ack, clk, rst, sig);
  reg \$auto$verilog_backend.cc:2082:dump_module$8  = 0;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:85" *)
  wire [35:0] \$1 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$10 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$100 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$102 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$103 ;
  reg [1:0] \$105 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:117" *)
  wire [5:0] \$12 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:117" *)
  wire [5:0] \$13 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
  wire \$15 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:101" *)
  wire [8:0] \$17 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:101" *)
  wire [8:0] \$18 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:85" *)
  wire [35:0] \$2 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:101" *)
  wire [8:0] \$20 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
  wire \$22 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:102" *)
  wire [4:0] \$24 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:102" *)
  wire [4:0] \$25 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$27 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$29 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$31 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:111" *)
  wire [199:0] \$33 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:111" *)
  wire [199:0] \$35 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$37 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:112" *)
  wire [7:0] \$39 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
  wire \$4 ;
  (* src = "/home/git/amaranth/amaranth/back/rtlil.py:611" *)
  wire [8:0] \$40 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$43 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$45 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$46 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$48 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$49 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$51 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$52 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$54 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$55 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$57 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$58 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
  wire \$6 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$60 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$61 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$63 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$64 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$66 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$67 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$69 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$70 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$72 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$73 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$75 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$76 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$78 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$79 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:124" *)
  wire \$8 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$81 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$82 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$84 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$85 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$87 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$88 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$90 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$91 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$93 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$94 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$96 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$97 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
  wire [199:0] \$99 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:72" *)
  reg [3:0] bits = 4'h0;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:72" *)
  reg [3:0] \bits$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:9" *)
  reg [199:0] dup_fin;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:10" *)
  wire [199:0] dup_fout;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:11" *)
  reg [7:0] dup_rc;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
  reg [2:0] fsm_state = 3'h0;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
  reg [2:0] \fsm_state$next ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:71" *)
  reg [4:0] rn = 5'h00;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:71" *)
  reg [4:0] \rn$next ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:77" *)
  wire [143:0] roundc;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:61" *)
  input sig;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:74" *)
  reg [7:0] sigma = 8'h00;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:74" *)
  reg [7:0] \sigma$next ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:76" *)
  reg [199:0] state = 200'h00000000000000000000000000000000000000000000000000;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:76" *)
  reg [199:0] \state$next ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:63" *)
  output [31:0] z;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:65" *)
  input z_ack;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:64" *)
  output z_valid;
  reg z_valid = 1'h0;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:64" *)
  reg \z_valid$next ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:75" *)
  reg [35:0] zc = 36'h000000000;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:75" *)
  reg [35:0] \zc$next ;
  assign \$100  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$103  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$10  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$13  = rn + (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:117" *) 1'h1;
  assign \$15  = bits == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *) 4'h8;
  assign \$20  = \$18  | (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:101" *) sig;
  assign \$22  = bits == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *) 4'h8;
  assign \$25  = bits + (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:102" *) 1'h1;
  assign \$27  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$29  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$31  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$33  = state ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:111" *) sigma;
  assign \$35  = \$33  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:111" *) 10'h201;
  assign \$37  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$40  = rn * (* src = "/home/git/amaranth/amaranth/back/rtlil.py:611" *) 4'h8;
  assign \$39  = 144'h800203898b8b0a09888a0981018b008a8201 >> \$40 ;
  assign \$43  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$46  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$4  = bits == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *) 4'h8;
  assign \$49  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$52  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$55  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$58  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$61  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$64  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$67  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$6  = rn == (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *) 5'h12;
  assign \$70  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$73  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$76  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$79  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$82  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$85  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$88  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$8  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:124" *) z_ack;
  assign \$91  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$94  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  assign \$97  = dup_fout & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *) 2'h3;
  always @(posedge clk)
    zc <= \zc$next ;
  always @(posedge clk)
    z_valid <= \z_valid$next ;
  always @(posedge clk)
    state <= \state$next ;
  always @(posedge clk)
    bits <= \bits$next ;
  always @(posedge clk)
    sigma <= \sigma$next ;
  always @(posedge clk)
    rn <= \rn$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  dup dup (
    .fin(dup_fin),
    .fout(dup_fout),
    .rc(dup_rc)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \zc$next  = zc;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          /* empty */;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$43 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                (* full_case = 32'd1 *)
                (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:116" *)
                casez (rn)
                  5'h00:
                      \zc$next [1:0] = \$49 [1:0];
                  5'h01:
                      \zc$next [3:2] = \$52 [1:0];
                  5'h02:
                      \zc$next [5:4] = \$55 [1:0];
                  5'h03:
                      \zc$next [7:6] = \$58 [1:0];
                  5'h04:
                      \zc$next [9:8] = \$61 [1:0];
                  5'h05:
                      \zc$next [11:10] = \$64 [1:0];
                  5'h06:
                      \zc$next [13:12] = \$67 [1:0];
                  5'h07:
                      \zc$next [15:14] = \$70 [1:0];
                  5'h08:
                      \zc$next [17:16] = \$73 [1:0];
                  5'h09:
                      \zc$next [19:18] = \$76 [1:0];
                  5'h0a:
                      \zc$next [21:20] = \$79 [1:0];
                  5'h0b:
                      \zc$next [23:22] = \$82 [1:0];
                  5'h0c:
                      \zc$next [25:24] = \$85 [1:0];
                  5'h0d:
                      \zc$next [27:26] = \$88 [1:0];
                  5'h0e:
                      \zc$next [29:28] = \$91 [1:0];
                  5'h0f:
                      \zc$next [31:30] = \$94 [1:0];
                  5'h10:
                      \zc$next [33:32] = \$97 [1:0];
                  5'h11:
                      \zc$next [35:34] = \$100 [1:0];
                  5'h??:
                      \$105  = \$103 [1:0];
                endcase
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \zc$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          \fsm_state$next  = 3'h1;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
          casez (\$4 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" */
            1'h1:
                \fsm_state$next  = 3'h2;
          endcase
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$6 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                \fsm_state$next  = 3'h3;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                \fsm_state$next  = 3'h1;
          endcase
      /* \amaranth.decoding  = "STOP/3" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:119" */
      3'h3:
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:120" *)
          casez (z_ack)
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:120" */
            1'h1:
                \fsm_state$next  = 3'h4;
          endcase
      /* \amaranth.decoding  = "DONE/4" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:123" */
      3'h4:
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:124" *)
          casez (\$8 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:124" */
            1'h1:
                \fsm_state$next  = 3'h0;
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \rn$next  = rn;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          \rn$next  = 5'h00;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$10 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                \rn$next  = \$13 [4:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \rn$next  = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \sigma$next  = sigma;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          \sigma$next  = 8'h00;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
          casez (\$15 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:99" */
            default:
                \sigma$next  = \$20 [7:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sigma$next  = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \bits$next  = bits;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          \bits$next  = 4'h0;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" *)
          casez (\$22 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:96" */
            1'h1:
                \bits$next  = 4'h0;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:99" */
            default:
                \bits$next  = \$25 [3:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \bits$next  = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \state$next  = state;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          \state$next  = 200'h00000000000000000000000000000000000000000000000000;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$27 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                \state$next  = dup_fout;
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \state$next  = 200'h00000000000000000000000000000000000000000000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    \z_valid$next  = z_valid;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          /* empty */;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$29 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                \z_valid$next  = 1'h1;
          endcase
      /* \amaranth.decoding  = "STOP/3" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:119" */
      3'h3:
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:120" *)
          casez (z_ack)
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:120" */
            1'h1:
                \z_valid$next  = 1'h0;
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \z_valid$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    dup_fin = 200'h00000000000000000000000000000000000000000000000000;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          /* empty */;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$31 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                dup_fin = \$35 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$8 ) begin end
    dup_rc = 8'h00;
    (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:86" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "START/0" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:87" */
      3'h0:
          /* empty */;
      /* \amaranth.decoding  = "COLLECT/1" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:95" */
      3'h1:
          /* empty */;
      /* \amaranth.decoding  = "DUPLEX/2" */
      /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:104" */
      3'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" *)
          casez (\$37 )
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:105" */
            1'h1:
                /* empty */;
            /* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:108" */
            default:
                dup_rc = \$39 ;
          endcase
    endcase
  end
  assign \$1  = \$2 ;
  assign \$12  = \$13 ;
  assign \$17  = \$20 ;
  assign \$24  = \$25 ;
  assign \$45  = \$46 ;
  assign \$48  = \$49 ;
  assign \$51  = \$52 ;
  assign \$54  = \$55 ;
  assign \$57  = \$58 ;
  assign \$60  = \$61 ;
  assign \$63  = \$64 ;
  assign \$66  = \$67 ;
  assign \$69  = \$70 ;
  assign \$72  = \$73 ;
  assign \$75  = \$76 ;
  assign \$78  = \$79 ;
  assign \$81  = \$82 ;
  assign \$84  = \$85 ;
  assign \$87  = \$88 ;
  assign \$90  = \$91 ;
  assign \$93  = \$94 ;
  assign \$96  = \$97 ;
  assign \$99  = \$100 ;
  assign \$102  = \$103 ;
  assign z = \$2 [31:0];
  assign roundc[143:136] = 8'h80;
  assign roundc[135:128] = 8'h02;
  assign roundc[127:120] = 8'h03;
  assign roundc[119:112] = 8'h89;
  assign roundc[111:104] = 8'h8b;
  assign roundc[103:96] = 8'h8b;
  assign roundc[95:88] = 8'h0a;
  assign roundc[87:80] = 8'h09;
  assign roundc[79:72] = 8'h88;
  assign roundc[71:64] = 8'h8a;
  assign roundc[63:56] = 8'h09;
  assign roundc[55:48] = 8'h81;
  assign roundc[47:40] = 8'h01;
  assign roundc[39:32] = 8'h8b;
  assign roundc[31:24] = 8'h00;
  assign roundc[23:16] = 8'h8a;
  assign roundc[15:8] = 8'h82;
  assign roundc[7:0] = 8'h01;
  assign \$2  = { 4'h0, zc[35:4] };
  assign \$18  = { sigma, 1'h0 };
endmodule

(* \amaranth.hierarchy  = "DuplexingPP.dup" *)
(* generator = "Amaranth" *)
module dup(rc, fout, fin);
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$1 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$10 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *)
  wire [7:0] \$100 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$103 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$106 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$109 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$112 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$115 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *)
  wire [7:0] \$118 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$12 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$121 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$124 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$127 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$130 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$133 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$14 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$16 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$161 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$163 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$165 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$168 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$170 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$172 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$175 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$177 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$179 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$182 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$184 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$186 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$189 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$19 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$191 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$193 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$196 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$198 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$200 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$203 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$205 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$207 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$21 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$210 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$212 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$214 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$217 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$219 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$221 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$224 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$226 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$228 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$23 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$231 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$233 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$235 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$238 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$240 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$242 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$245 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$247 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$249 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$25 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$252 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$254 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$256 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$259 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$261 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$263 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$266 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$268 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$270 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$273 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$275 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$277 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$28 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$280 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$282 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$284 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$287 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$289 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$291 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$294 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$296 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$298 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$3 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$30 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$301 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$303 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$305 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$308 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$310 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$312 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$315 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$317 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$319 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$32 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$322 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$324 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$326 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$329 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$331 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *)
  wire [7:0] \$333 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:49" *)
  wire [7:0] \$335 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$34 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$37 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$39 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$41 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$43 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *)
  wire [7:0] \$46 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$49 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$5 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$52 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$55 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$58 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$61 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *)
  wire [7:0] \$64 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$67 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *)
  wire [7:0] \$7 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$70 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$73 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$76 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$79 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *)
  wire [7:0] \$82 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$85 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$88 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$91 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$94 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *)
  wire [7:0] \$97 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:16" *)
  wire [7:0] \$signal ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$102 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$105 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$108 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$111 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$114 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:17" *)
  wire [7:0] \$signal$117 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$120 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$123 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$126 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$129 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$132 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$135 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$136 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$137 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$138 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$139 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$140 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$141 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$142 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$143 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$144 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$145 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$146 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$147 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$148 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$149 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$150 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$151 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$152 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$153 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$154 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$155 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$156 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$157 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$158 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:19" *)
  wire [7:0] \$signal$159 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$160 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$167 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$174 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:16" *)
  wire [7:0] \$signal$18 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$181 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$188 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$195 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$202 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$209 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$216 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$223 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$230 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$237 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$244 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$251 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$258 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$265 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:16" *)
  wire [7:0] \$signal$27 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$272 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$279 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$286 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$293 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$300 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$307 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$314 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$321 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:20" *)
  wire [7:0] \$signal$328 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:16" *)
  wire [7:0] \$signal$36 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:17" *)
  wire [7:0] \$signal$45 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$48 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$51 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$54 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$57 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$60 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:17" *)
  wire [7:0] \$signal$63 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$66 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$69 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$72 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$75 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$78 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:17" *)
  wire [7:0] \$signal$81 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$84 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$87 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:16" *)
  wire [7:0] \$signal$9 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$90 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$93 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:18" *)
  wire [7:0] \$signal$96 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:17" *)
  wire [7:0] \$signal$99 ;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:9" *)
  input [199:0] fin;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:10" *)
  output [199:0] fout;
  (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:11" *)
  input [7:0] rc;
  assign \$100  = \$signal$18  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *) { \$signal$36 [6:0], \$signal$36 [7] };
  assign \$103  = fin[31:24] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$99 ;
  assign \$106  = fin[71:64] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$99 ;
  assign \$10  = fin[15:8] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[55:48];
  assign \$109  = fin[111:104] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$99 ;
  assign \$112  = fin[151:144] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$99 ;
  assign \$115  = fin[191:184] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$99 ;
  assign \$118  = \$signal$27  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *) { \$signal [6:0], \$signal [7] };
  assign \$121  = fin[39:32] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$117 ;
  assign \$124  = fin[79:72] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$117 ;
  assign \$127  = fin[119:112] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$117 ;
  assign \$12  = \$10  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[95:88];
  assign \$130  = fin[159:152] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$117 ;
  assign \$133  = fin[199:192] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$117 ;
  assign \$14  = \$12  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[135:128];
  assign \$161  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$159 ;
  assign \$163  = \$161  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$153 ;
  assign \$165  = \$signal$135  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$163 ;
  assign \$168  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$153 ;
  assign \$16  = \$14  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[175:168];
  assign \$170  = \$168  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$141 ;
  assign \$172  = \$signal$159  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$170 ;
  assign \$175  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$141 ;
  assign \$177  = \$175  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$147 ;
  assign \$179  = \$signal$153  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$177 ;
  assign \$182  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$147 ;
  assign \$184  = \$182  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$135 ;
  assign \$186  = \$signal$141  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$184 ;
  assign \$189  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$135 ;
  assign \$191  = \$189  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$159 ;
  assign \$193  = \$signal$147  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$191 ;
  assign \$196  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$158 ;
  assign \$198  = \$196  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$137 ;
  assign \$1  = fin[7:0] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[47:40];
  assign \$19  = fin[23:16] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[63:56];
  assign \$200  = \$signal$142  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$198 ;
  assign \$203  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$137 ;
  assign \$205  = \$203  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$144 ;
  assign \$207  = \$signal$158  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$205 ;
  assign \$210  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$144 ;
  assign \$212  = \$210  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$157 ;
  assign \$214  = \$signal$137  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$212 ;
  assign \$217  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$157 ;
  assign \$21  = \$19  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[103:96];
  assign \$219  = \$217  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$142 ;
  assign \$221  = \$signal$144  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$219 ;
  assign \$224  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$142 ;
  assign \$226  = \$224  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$158 ;
  assign \$228  = \$signal$157  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$226 ;
  assign \$231  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$138 ;
  assign \$233  = \$231  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$152 ;
  assign \$235  = \$signal$136  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$233 ;
  assign \$238  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$152 ;
  assign \$23  = \$21  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[143:136];
  assign \$240  = \$238  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$151 ;
  assign \$242  = \$signal$138  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$240 ;
  assign \$245  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$151 ;
  assign \$247  = \$245  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$155 ;
  assign \$249  = \$signal$152  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$247 ;
  assign \$252  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$155 ;
  assign \$254  = \$252  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$136 ;
  assign \$256  = \$signal$151  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$254 ;
  assign \$25  = \$23  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[183:176];
  assign \$259  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$136 ;
  assign \$261  = \$259  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$138 ;
  assign \$263  = \$signal$155  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$261 ;
  assign \$266  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$143 ;
  assign \$268  = \$266  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$139 ;
  assign \$270  = \$signal$148  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$268 ;
  assign \$273  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$139 ;
  assign \$275  = \$273  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$140 ;
  assign \$277  = \$signal$143  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$275 ;
  assign \$280  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$140 ;
  assign \$282  = \$280  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$150 ;
  assign \$284  = \$signal$139  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$282 ;
  assign \$287  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$150 ;
  assign \$28  = fin[31:24] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[71:64];
  assign \$289  = \$287  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$148 ;
  assign \$291  = \$signal$140  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$289 ;
  assign \$294  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$148 ;
  assign \$296  = \$294  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$143 ;
  assign \$298  = \$signal$150  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$296 ;
  assign \$301  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$145 ;
  assign \$303  = \$301  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$156 ;
  assign \$305  = \$signal$154  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$303 ;
  assign \$308  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$156 ;
  assign \$30  = \$28  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[111:104];
  assign \$310  = \$308  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$149 ;
  assign \$312  = \$signal$145  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$310 ;
  assign \$315  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$149 ;
  assign \$317  = \$315  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$146 ;
  assign \$319  = \$signal$156  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$317 ;
  assign \$322  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$146 ;
  assign \$324  = \$322  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$154 ;
  assign \$326  = \$signal$149  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$324 ;
  assign \$32  = \$30  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[151:144];
  assign \$329  = ~ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$154 ;
  assign \$331  = \$329  & (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$signal$145 ;
  assign \$333  = \$signal$146  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:43" *) \$331 ;
  assign \$335  = \$signal$160  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:49" *) rc;
  assign \$34  = \$32  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[191:184];
  assign \$37  = fin[39:32] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[79:72];
  assign \$3  = \$1  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[87:80];
  assign \$39  = \$37  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[119:112];
  assign \$41  = \$39  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[159:152];
  assign \$43  = \$41  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[199:192];
  assign \$46  = \$signal$36  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *) { \$signal$9 [6:0], \$signal$9 [7] };
  assign \$49  = fin[7:0] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$45 ;
  assign \$52  = fin[47:40] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$45 ;
  assign \$55  = fin[87:80] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$45 ;
  assign \$58  = fin[127:120] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$45 ;
  assign \$5  = \$3  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[127:120];
  assign \$61  = fin[167:160] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$45 ;
  assign \$64  = \$signal  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *) { \$signal$18 [6:0], \$signal$18 [7] };
  assign \$67  = fin[15:8] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$63 ;
  assign \$70  = fin[55:48] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$63 ;
  assign \$73  = fin[95:88] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$63 ;
  assign \$76  = fin[135:128] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$63 ;
  assign \$7  = \$5  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:25" *) fin[167:160];
  assign \$79  = fin[175:168] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$63 ;
  assign \$82  = \$signal$9  ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:28" *) { \$signal$27 [6:0], \$signal$27 [7] };
  assign \$85  = fin[23:16] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$81 ;
  assign \$88  = fin[63:56] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$81 ;
  assign \$91  = fin[103:96] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$81 ;
  assign \$94  = fin[143:136] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$81 ;
  assign \$97  = fin[183:176] ^ (* src = "/home/git/lwtrng/lwtrng/pp/verilog/../duplexing.py:30" *) \$signal$81 ;
  assign fout[7:0] = \$335 ;
  assign fout[199:192] = \$signal$328 ;
  assign fout[191:184] = \$signal$321 ;
  assign fout[183:176] = \$signal$314 ;
  assign fout[175:168] = \$signal$307 ;
  assign fout[167:160] = \$signal$300 ;
  assign fout[159:152] = \$signal$293 ;
  assign fout[151:144] = \$signal$286 ;
  assign fout[143:136] = \$signal$279 ;
  assign fout[135:128] = \$signal$272 ;
  assign fout[127:120] = \$signal$265 ;
  assign fout[119:112] = \$signal$258 ;
  assign fout[111:104] = \$signal$251 ;
  assign fout[103:96] = \$signal$244 ;
  assign fout[95:88] = \$signal$237 ;
  assign fout[87:80] = \$signal$230 ;
  assign fout[79:72] = \$signal$223 ;
  assign fout[71:64] = \$signal$216 ;
  assign fout[63:56] = \$signal$209 ;
  assign fout[55:48] = \$signal$202 ;
  assign fout[47:40] = \$signal$195 ;
  assign fout[39:32] = \$signal$188 ;
  assign fout[31:24] = \$signal$181 ;
  assign fout[23:16] = \$signal$174 ;
  assign fout[15:8] = \$signal$167 ;
  assign \$signal$328  = \$333 ;
  assign \$signal$321  = \$326 ;
  assign \$signal$314  = \$319 ;
  assign \$signal$307  = \$312 ;
  assign \$signal$300  = \$305 ;
  assign \$signal$293  = \$298 ;
  assign \$signal$286  = \$291 ;
  assign \$signal$279  = \$284 ;
  assign \$signal$272  = \$277 ;
  assign \$signal$265  = \$270 ;
  assign \$signal$258  = \$263 ;
  assign \$signal$251  = \$256 ;
  assign \$signal$244  = \$249 ;
  assign \$signal$237  = \$242 ;
  assign \$signal$230  = \$235 ;
  assign \$signal$223  = \$228 ;
  assign \$signal$216  = \$221 ;
  assign \$signal$209  = \$214 ;
  assign \$signal$202  = \$207 ;
  assign \$signal$195  = \$200 ;
  assign \$signal$188  = \$193 ;
  assign \$signal$181  = \$186 ;
  assign \$signal$174  = \$179 ;
  assign \$signal$167  = \$172 ;
  assign \$signal$160  = \$165 ;
  assign \$signal$159  = { \$signal$69 [3:0], \$signal$69 [7:4] };
  assign \$signal$158  = { \$signal$123 [3:0], \$signal$123 [7:4] };
  assign \$signal$157  = { \$signal$96 [2:0], \$signal$96 [7:3] };
  assign \$signal$156  = { \$signal$126 [0], \$signal$126 [7:1] };
  assign \$signal$155  = { \$signal$60 [5:0], \$signal$60 [7:6] };
  assign \$signal$154  = { \$signal$84 [1:0], \$signal$84 [7:2] };
  assign \$signal$153  = { \$signal$90 [4:0], \$signal$90 [7:5] };
  assign \$signal$152  = { \$signal$108 [6:0], \$signal$108 [7] };
  assign \$signal$151  = \$signal$129 ;
  assign \$signal$150  = \$signal$114 ;
  assign \$signal$149  = { \$signal$57 [6:0], \$signal$57 [7] };
  assign \$signal$148  = { \$signal$120 [4:0], \$signal$120 [7:5] };
  assign \$signal$147  = { \$signal$132 [1:0], \$signal$132 [7:2] };
  assign \$signal$146  = { \$signal$78 [5:0], \$signal$78 [7:6] };
  assign \$signal$145  = { \$signal$105 [0], \$signal$105 [7:1] };
  assign \$signal$144  = { \$signal$75 [2:0], \$signal$75 [7:3] };
  assign \$signal$143  = { \$signal$51 [3:0], \$signal$51 [7:4] };
  assign \$signal$142  = { \$signal$102 [3:0], \$signal$102 [7:4] };
  assign \$signal$141  = { \$signal$111 [2:0], \$signal$111 [7:3] };
  assign \$signal$140  = { \$signal$93 [0], \$signal$93 [7:1] };
  assign \$signal$139  = { \$signal$72 [5:0], \$signal$72 [7:6] };
  assign \$signal$138  = { \$signal$87 [1:0], \$signal$87 [7:2] };
  assign \$signal$137  = { \$signal$54 [4:0], \$signal$54 [7:5] };
  assign \$signal$136  = { \$signal$66 [6:0], \$signal$66 [7] };
  assign \$signal$135  = \$signal$48 ;
  assign \$signal$132  = \$133 ;
  assign \$signal$129  = \$130 ;
  assign \$signal$126  = \$127 ;
  assign \$signal$123  = \$124 ;
  assign \$signal$120  = \$121 ;
  assign \$signal$117  = \$118 ;
  assign \$signal$114  = \$115 ;
  assign \$signal$111  = \$112 ;
  assign \$signal$108  = \$109 ;
  assign \$signal$105  = \$106 ;
  assign \$signal$102  = \$103 ;
  assign \$signal$99  = \$100 ;
  assign \$signal$96  = \$97 ;
  assign \$signal$93  = \$94 ;
  assign \$signal$90  = \$91 ;
  assign \$signal$87  = \$88 ;
  assign \$signal$84  = \$85 ;
  assign \$signal$81  = \$82 ;
  assign \$signal$78  = \$79 ;
  assign \$signal$75  = \$76 ;
  assign \$signal$72  = \$73 ;
  assign \$signal$69  = \$70 ;
  assign \$signal$66  = \$67 ;
  assign \$signal$63  = \$64 ;
  assign \$signal$60  = \$61 ;
  assign \$signal$57  = \$58 ;
  assign \$signal$54  = \$55 ;
  assign \$signal$51  = \$52 ;
  assign \$signal$48  = \$49 ;
  assign \$signal$45  = \$46 ;
  assign \$signal$36  = \$43 ;
  assign \$signal$27  = \$34 ;
  assign \$signal$18  = \$25 ;
  assign \$signal$9  = \$16 ;
  assign \$signal  = \$7 ;
endmodule

